ALTER TABLE metabase.metabase_field ADD CONSTRAINT fk_field_parent_ref_field_id FOREIGN KEY (parent_id) REFERENCES metabase.metabase_field (id);
ALTER TABLE metabase.report_card ADD CONSTRAINT fk_report_card_ref_database_id FOREIGN KEY (database_id) REFERENCES metabase.metabase_database (id);
ALTER TABLE metabase.report_card ADD CONSTRAINT fk_report_card_ref_table_id FOREIGN KEY (table_id) REFERENCES metabase.metabase_table (id);
ALTER TABLE metabase.report_card ADD CONSTRAINT fk_card_collection_id FOREIGN KEY (collection_id) REFERENCES metabase.collection (id);
ALTER TABLE metabase.report_card ADD CONSTRAINT fk_card_made_public_by_id FOREIGN KEY (made_public_by_id) REFERENCES metabase.core_user (id);
ALTER TABLE metabase.report_dashboard ADD CONSTRAINT fk_dashboard_made_public_by_id FOREIGN KEY (made_public_by_id) REFERENCES metabase.core_user (id);
ALTER TABLE metabase.report_dashboard ADD CONSTRAINT fk_dashboard_collection_id FOREIGN KEY (collection_id) REFERENCES metabase.collection (id);
ALTER TABLE metabase.pulse ADD CONSTRAINT fk_pulse_collection_id FOREIGN KEY (collection_id) REFERENCES metabase.collection (id);
ALTER TABLE metabase.collection ADD CONSTRAINT fk_collection_personal_owner_id FOREIGN KEY (personal_owner_id) REFERENCES metabase.core_user (id);
ALTER TABLE metabase.QRTZ_TRIGGERS ADD CONSTRAINT FK_QRTZ_TRIGGERS_JOB_DETAILS FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP) REFERENCES metabase.QRTZ_JOB_DETAILS (SCHED_NAME, JOB_NAME, JOB_GROUP);
ALTER TABLE metabase.QRTZ_SIMPLE_TRIGGERS ADD CONSTRAINT FK_QRTZ_SIMPLE_TRIGGERS_TRIGGERS FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES metabase.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);
ALTER TABLE metabase.QRTZ_CRON_TRIGGERS ADD CONSTRAINT FK_QRTZ_CRON_TRIGGERS_TRIGGERS FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES metabase.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);
ALTER TABLE metabase.QRTZ_SIMPROP_TRIGGERS ADD CONSTRAINT FK_QRTZ_SIMPROP_TRIGGERS_TRIGGERS FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES metabase.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);
ALTER TABLE metabase.QRTZ_BLOB_TRIGGERS ADD CONSTRAINT FK_QRTZ_BLOB_TRIGGERS_TRIGGERS FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES metabase.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);
ALTER TABLE metabase.metabase_table ADD CONSTRAINT fk_table_ref_database_id FOREIGN KEY (db_id) REFERENCES metabase.metabase_database(id );
ALTER TABLE metabase.metabase_field ADD CONSTRAINT fk_field_ref_table_id FOREIGN KEY (table_id) REFERENCES metabase.metabase_table(id );
ALTER TABLE metabase.metabase_fieldvalues ADD CONSTRAINT fk_fieldvalues_ref_field_id FOREIGN KEY (field_id) REFERENCES metabase.metabase_field(id );
ALTER TABLE metabase.report_cardfavorite ADD CONSTRAINT fk_cardfavorite_ref_card_id FOREIGN KEY (card_id) REFERENCES metabase.report_card(id );
ALTER TABLE metabase.report_dashboardcard ADD CONSTRAINT fk_dashboardcard_ref_dashboard_id FOREIGN KEY (dashboard_id) REFERENCES metabase.report_dashboard(id );
ALTER TABLE metabase.core_session ADD CONSTRAINT fk_session_ref_user_id FOREIGN KEY (user_id) REFERENCES metabase.core_user(id );
ALTER TABLE metabase.revision ADD CONSTRAINT fk_revision_ref_user_id FOREIGN KEY (user_id) REFERENCES metabase.core_user(id );
ALTER TABLE metabase.activity ADD CONSTRAINT fk_activity_ref_user_id FOREIGN KEY (user_id) REFERENCES metabase.core_user(id );
ALTER TABLE metabase.pulse ADD CONSTRAINT fk_pulse_ref_creator_id FOREIGN KEY (creator_id) REFERENCES metabase.core_user(id );
ALTER TABLE metabase.pulse_card ADD CONSTRAINT fk_pulse_card_ref_card_id FOREIGN KEY (card_id) REFERENCES metabase.report_card(id );
ALTER TABLE metabase.pulse_channel ADD CONSTRAINT fk_pulse_channel_ref_pulse_id FOREIGN KEY (pulse_id) REFERENCES metabase.pulse(id );
ALTER TABLE metabase.pulse_channel_recipient ADD CONSTRAINT fk_pulse_channel_recipient_ref_user_id FOREIGN KEY (user_id) REFERENCES metabase.core_user(id );
ALTER TABLE metabase.segment ADD CONSTRAINT fk_segment_ref_table_id FOREIGN KEY (table_id) REFERENCES metabase.metabase_table(id );
ALTER TABLE metabase.segment ADD CONSTRAINT fk_segment_ref_creator_id FOREIGN KEY (creator_id) REFERENCES metabase.core_user(id);
ALTER TABLE metabase.metric ADD CONSTRAINT fk_metric_ref_creator_id FOREIGN KEY (creator_id) REFERENCES metabase.core_user(id );
ALTER TABLE metabase.metric ADD CONSTRAINT fk_metric_ref_table_id FOREIGN KEY (table_id) REFERENCES metabase.metabase_table(id);
ALTER TABLE metabase.dashboardcard_series ADD CONSTRAINT fk_dashboardcard_series_ref_card_id FOREIGN KEY (card_id) REFERENCES metabase.report_card(id );
ALTER TABLE metabase.dashboardcard_series ADD CONSTRAINT fk_dashboardcard_series_ref_dashboardcard_id FOREIGN KEY (dashboardcard_id) REFERENCES metabase.report_dashboardcard(id)
ALTER TABLE metabase.card_label ADD CONSTRAINT fk_card_label_ref_card_id FOREIGN KEY (card_id) REFERENCES metabase.report_card(id );
ALTER TABLE metabase.metric_important_field ADD CONSTRAINT fk_metric_important_field_metabase_field_id FOREIGN KEY (field_id) REFERENCES metabase.metabase_field(id );
ALTER TABLE metabase.permissions_group_membership ADD CONSTRAINT fk_permissions_group_group_id FOREIGN KEY (group_id) REFERENCES metabase.permissions_group(id );
ALTER TABLE metabase.permissions ADD CONSTRAINT fk_permissions_group_id FOREIGN KEY (group_id) REFERENCES metabase.permissions_group(id );
ALTER TABLE metabase.permissions_revision ADD CONSTRAINT fk_permissions_revision_user_id FOREIGN KEY (user_id) REFERENCES metabase.core_user(id );
ALTER TABLE metabase.collection_revision ADD CONSTRAINT fk_collection_revision_user_id FOREIGN KEY (user_id) REFERENCES metabase.core_user(id );
ALTER TABLE metabase.dashboard_favorite ADD CONSTRAINT fk_dashboard_favorite_user_id FOREIGN KEY (user_id) REFERENCES metabase.core_user(id) ON DELETE CASCADE);
ALTER TABLE metabase.dimension ADD CONSTRAINT fk_dimension_ref_field_id FOREIGN KEY (field_id) REFERENCES metabase.metabase_field(id) ON DELETE CASCADE);
ALTER TABLE metabase.computation_job ADD CONSTRAINT fk_computation_job_ref_user_id FOREIGN KEY (creator_id) REFERENCES metabase.core_user(id );
ALTER TABLE metabase.computation_job_result ADD CONSTRAINT fk_computation_result_ref_job_id FOREIGN KEY (job_id) REFERENCES metabase.computation_job(id );
ALTER TABLE metabase.pulse_card ADD CONSTRAINT fk_pulse_card_ref_card_id FOREIGN KEY (card_id) REFERENCES metabase.report_card(id);
ALTER TABLE metabase.pulse_channel_recipient ADD CONSTRAINT fk_pulse_channel_recipient_ref_user_id FOREIGN KEY (user_id) REFERENCES metabase.core_user(id);
ALTER TABLE metabase.pulse_channel_recipient ADD  CONSTRAINT fk_pulse_channel_recipient_ref_pulse_channel_id FOREIGN KEY (pulse_channel_id) REFERENCES metabase.pulse_channel(id);
ALTER TABLE metabase.report_card ADD CONSTRAINT fk_card_ref_user_id FOREIGN KEY (creator_id) REFERENCES metabase.core_user(id);
ALTER TABLE metabase.report_cardfavorite ADD CONSTRAINT fk_cardfavorite_ref_user_id FOREIGN KEY (owner_id) REFERENCES metabase.core_user(id);
ALTER TABLE metabase.report_dashboard ADD CONSTRAINT fk_dashboard_ref_user_id FOREIGN KEY (creator_id) REFERENCES metabase.core_user(id);
ALTER TABLE metabase.report_dashboardcard ADD CONSTRAINT fk_dashboardcard_ref_card_id FOREIGN KEY (card_id) REFERENCES metabase.report_card(id);
ALTER TABLE metabase.card_label ADD CONSTRAINT fk_card_label_ref_label_id FOREIGN KEY (label_id) REFERENCES metabase.label(id);
ALTER TABLE metabase.metric_important_field ADD CONSTRAINT fk_metric_important_field_metric_id FOREIGN KEY (metric_id) REFERENCES metabase.metric(id);
ALTER TABLE metabase.permissions_group_membership ADD CONSTRAINT fk_permissions_group_membership_user_id FOREIGN KEY (user_id) REFERENCES metabase.core_user(id);
ALTER TABLE metabase.dashboard_favorite ADD CONSTRAINT fk_dashboard_favorite_dashboard_id FOREIGN KEY (dashboard_id) REFERENCES metabase.report_dashboard(id) ON DELETE CASCADE;
ALTER TABLE metabase.dimension ADD CONSTRAINT fk_dimension_displayfk_ref_field_id FOREIGN KEY (human_readable_field_id) REFERENCES metabase.metabase_field(id) ON DELETE CASCADE;
ALTER TABLE metabase.pulse_card ADD CONSTRAINT fk_pulse_card_ref_pulse_id FOREIGN KEY (pulse_id) REFERENCES metabase.pulse(id);